language : c
compiler : gcc

script : make

before_install:
- pip install --user cpp-coveralls

after_success:
   - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications :
    email : flaesch.arnaud@esgi.fr